---
title: "phylogeny"
author: "Ashley"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library("janitor")
library("hrbrthemes")
library("psych")
library("ggrepel")
library("ggplot2")
library("ggpubr")
library("broom")
library("AICcmodavg")
library("ctv") 
library("ape")
library("phytools")
library("phangorn")
library("geiger")
library("nlme")
library("ggtree")
```

```{r}
lh <- read_csv("Pantheria_og.csv")
pi <- read.csv("placenta__more_interdigitation.csv")
np <- read.csv("neoplasiaPrevalence.min10.2022-04-01T19_13.csv")
tree <- ape::read.nexus("mammals_phylo.txt")
mammals <- read.newick("mammals_species.nwk")
```

Cleaning Data
```{r}
# Selecting & renaming variables
lh <- lh %>%
  clean_names()

# rename variable & convert from months to days
lh2 <- lh %>%
  select(msw93_binomial, x3_1_ageat_first_birth_d, x9_1_gestation_len_d, x14_1_inter_birth_interval_d, x15_1_litter_size, x16_1_litters_per_year, x17_1_max_longevity_m, x23_1_sexual_maturity_age_d)%>%
  rename(species = "msw93_binomial") %>%
  rename(agefb = "x3_1_ageat_first_birth_d") %>%
  rename(gestation = "x9_1_gestation_len_d") %>%
  rename(interv = "x14_1_inter_birth_interval_d") %>%
  rename(littersize = "x15_1_litter_size") %>%
  rename(litterpyr = "x16_1_litters_per_year") %>%
  rename(longev = "x17_1_max_longevity_m") %>%
  rename(sexmat = "x23_1_sexual_maturity_age_d")%>%
  mutate(longev *30)%>%
  rename(longevd = "longev * 30")

pi2 <- pi %>%
  select(species, placenta_invasiveness, X.4, interdigitation_placenta, X.5)

pi2$invade = pi2$X.4
pi2$invade[pi2$invade == "1"] <- "4"
pi2$invade[pi2$invade == "3"] <- "1"
pi2$invade[pi2$invade == "4"] <- "3"

pi2$digit = pi2$X.5
pi2$digit[pi2$digit == "1"] <- "4"
pi2$digit[pi2$digit == "3"] <- "1"
pi2$digit[pi2$digit == "2"] <- "0"
pi2$digit[pi2$digit == "1"] <- "2"
pi2$digit[pi2$digit == "0"] <- "1"
pi2$digit[pi2$digit == "4"] <- "3"

pi3 <- pi2 %>%
  select(species, placenta_invasiveness, invade, interdigitation_placenta, digit)

np2 <- np %>%
  select(KeepWildRecords.false, X.5, X.7, X.9, X.10, X.11) %>%
  rename(species = "KeepWildRecords.false") %>%
  rename(tot.neo = "X.5") %>%
  rename(prev.neo = "X.7") %>%
  rename(tot.mal = "X.9") %>%
  rename(prev.mal = "X.10") %>%
  rename(mal.trans = "X.11")

# Life history + placental invasion/interdigitation
combo1 <- merge(lh2, pi3, by= "species")

anticombo1 <- anti_join(lh2, pi3, by = "species")

# Life history + placental invasion/interdigitation + neoplasia/malignancy
megaset <- merge(combo1, np2, by= "species")

antimega <- anti_join(combo1, np2, by= "species")

# Filter out missing values
combo2 <- combo1 %>%
  filter(!agefb==-999.00) %>%
  filter(!gestation==-999.00) %>%
  filter(!gestation==-999.00) %>%
  filter(!interv==-999.00) %>%
  filter(!litterpyr==-999.00) %>%
  filter(!longev==-999.00) %>%
  filter(!sexmat==-999.00)
# Only 53 species with complete data!


# Life history + Cancer data
lifecancer <- merge(lh2, np2, by = "species")
lifecancer$tot.neo <- as.numeric(lifecancer$tot.neo)
lifecancer$prev.neo <- as.numeric(lifecancer$prev.neo)
lifecancer$tot.mal <- as.numeric(lifecancer$tot.mal)
lifecancer$prev.mal <- as.numeric(lifecancer$prev.mal)
lifecancer$mal.trans <- as.numeric(lifecancer$mal.trans)

# Placentas + Cancer data
placentacancer <- merge(pi3, np2, by = "species")

placentacancer2 <- placentacancer1 %>%
  mutate_all(funs(str_replace(.," ","_")))

# Phylo
species_placcancer <- placentacancer2 %>%
  dplyr::select("species")

mammal_phy <- ggtree(tree$mammalST_bestDates)

mammal_phy <- as.phylo(mammal_phy)

species_phylo <- as.data.frame(mammal_phy$tip.label) %>%
  rename("species"="mammal_phy$tip.label")

species_kept <- merge(species_phylo, species_placcancer, by.x = "species", by.y = "species")

species_kept_v <- as.vector(species_kept$species)

small_mammal_k <- keep.tip(mammal_phy,species_kept_v)

write.csv(species_kept_v,"species_kept_v.csv", row.names = FALSE, col.names = TRUE)
species_kept_p <- read.csv("species_kept_v.csv")

placenta_num <- merge(species_kept_p, placentacancer2, by.x = "x", by.y = "species") %>%
  rename("species"=x)

# Mammals
mammals_list <- as.phylo(mammals)

specmammal <- as.data.frame(mammals_list$tip.label)%>%
  rename("species"="mammals_list$tip.label")

specieslist <- merge(specmammal, species_placcancer, by.x = "species", by.y = "species")

specieslist_v <- as.vector(specieslist$species)

specieslist_k <- keep.tip(mammals, specieslist_v)

write.csv(specieslist_v, "specieslist_v.csv", row.names = FALSE, col.names = TRUE)

specieskept <- read.csv("specieslist_v.csv")

mammallist <- merge(specieskept, placentacancer2, by.x = "x", by.y = "species")%>%
  rename("species"=x)

mammallist1 <- mammallist
mammallist1[is.na(mammallist1)] <- 0
```

Phylogeny
```{r}
malig <- mammallist1[, "mal.trans"]
interdig <- mammallist1[, "digit"]

malig1 <- as.numeric(malig)
interdig1 <- as.numeric(interdig)

pgls_interdig <- gls(malig1 ~ interdig1, correlation = corBrownian(phy = mammals_list), data = mammallist, method = "ML")
summary(pgls_interdig)

coef(pgls_interdig)

plot(malig1 ~ interdig1)
abline(a = coef(pgls_interdig)[1], b = coef(pgls_interdig)[2])

# w/ discrete predictor
pglsModel2 <- gls(malig1 ~ interdig1, correlation = corBrownian(phy = mammals_list),
    data = mammallist, method = "ML")
anova(pglsModel2)
coef(pglsModel2)
```